name: devsecops-pipeline

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: devsecops-jenkins
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      # Mount host docker socket so Jenkins can build and run docker containers
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_data:
